<script type="text/javascript" src="<?php echo $whiteboardpath;?>build/src/audio-g711-and-resampler.min.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/screendecode.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/screenworker.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/storage-array-base64-converter.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/worker-io.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/worker-audio-rec.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/worker-audio-send.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/worklet-audio-send.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/worklet-audio-rec.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/worker/webptopng.js"></script>

<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/wave.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/wave-mic.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/jquery-1.12.4.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/jquery-ui.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/handlebars-v4.0.8.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/codemirror.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/codemirror-continuelist.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/codemirror-xml.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/codemirror-markdown.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/mo_slickQuiz.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath."external/src/poll-d3.js" ?>"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath."external/src/poll-c3.js" ?>"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/video.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/youtube.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/videojs-contrib-hls.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath.'external/src/s3.fine-uploader.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/pdf.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/vhcheck.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>external/src/shadow-dom.js"></script>

<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/io.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/modernizr.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/roles.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/io-storage.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/io-missing-packets.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/io-adapter.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/io-ping-pong.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/virtualclass.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-canvas.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-utility.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/lang-en.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/lang.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/view.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/environment-validation.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-packetcontainer.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-drawobject.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-make-object.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-canvas-utility.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-canvas-main.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-events.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-virtualbox.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-interact.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-rectangle.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-oval.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-triangle.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-line.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-text.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-freedrawing.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-path.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-mouse.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-readyfreehandobj.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-refresh-play.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-readytextobj.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-keyboard.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/webrtc-adapter.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/media.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/pptshare.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-packet-queue.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-optimization.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/receive-messages-response.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/lzstring.js"></script>

<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/screenshare-getscreen.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/screenshare-dirtycorner.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/utility.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/screenshare.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/record-play.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/indexeddb-storage.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/footer-control-user.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/xhr.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/xhrn.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/popup.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/storage-array-base64-converter.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/progressbar.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-server.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-utils.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-rich-toolbar.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-text-op.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-text-operation.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-wrapped-operation.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-cursor.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-undo-manager.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-client.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-editor-client.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-span.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-annotation-list.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-attribute-constants.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-line-formatting.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-serialize-html.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor-parse-html.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-codemirror-adapter.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/ot-adapter.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/vceditor.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/editor.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/chat.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/chat-footer.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/jquery.ui.chatlist.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/jquery.ui.chatbox.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/jquery.ui.chatroom.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/chat-boxManager.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/chat-lib.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/chat-lang.en.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/precheck.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/video-base64.min.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/video-ajax.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/video-script.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/video-host.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/poll.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/dashboard.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/upload-video.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/congrea-uploader.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/page.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/document-share.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/quiz.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/doNotesMain.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/multi-video.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/zoom.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/pdf-render.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/whiteboard-common.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/server-data.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/api.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/raise-hand.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/color-selector.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/chroma.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/modernizr.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/app-settings.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/network.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/gesture.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/page-navigation.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/templates_view.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/modal.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/chat-container-event.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/mic-testing.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/common-xhr.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/settings.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/idb.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/user-join-operation.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/io-event-api.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/receive-function.js"></script>
<script type="text/javascript" src="<?php echo $whiteboardpath;?>src/index.js"></script>
